# Site settings
title: BETTER WORK APP
email: asanchezrodelgo@ifc.org
url: http://cismr.com
baseurl: 
description: "A collaboration between Better Work, Tufts University, and the World Bank"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: work better

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: youtube
#     url: https://www.youtube.com/
#   - title: twitter
#     url: https://twitter.com/bcndata
#   - title: facebook
#     url: https://www.facebook.com/krijn.paaijmans

# Build settings
markdown: kramdown
permalink: pretty
